// <auto-generated />
using System;
using API_Unit;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_Unit.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20201214175815_DBCretor")]
    partial class DBCretor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("API_Unit.Models.ReporterStation", b =>
                {
                    b.Property<int>("ReporterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<string>("ReporterTitel")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ReporterID");

                    b.ToTable("ReporterStations");
                });

            modelBuilder.Entity("API_Unit.Models.TagRegistered", b =>
                {
                    b.Property<long>("RowID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegisterdDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReporterID_FK")
                        .HasColumnType("int");

                    b.Property<int>("TagID_FK")
                        .HasColumnType("int");

                    b.Property<bool>("ViewRegistered")
                        .HasColumnType("bit");

                    b.HasKey("RowID");

                    b.HasIndex("ReporterID_FK");

                    b.HasIndex("TagID_FK");

                    b.ToTable("TagRegistereds");
                });

            modelBuilder.Entity("API_Unit.Models.Tags", b =>
                {
                    b.Property<int>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("TagTitel")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("TagID");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("API_Unit.Models.TagRegistered", b =>
                {
                    b.HasOne("API_Unit.Models.ReporterStation", "ReporterStation")
                        .WithMany("TagRegistereds")
                        .HasForeignKey("ReporterID_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Unit.Models.Tags", "Tags")
                        .WithMany("TagRegistereds")
                        .HasForeignKey("TagID_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReporterStation");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("API_Unit.Models.ReporterStation", b =>
                {
                    b.Navigation("TagRegistereds");
                });

            modelBuilder.Entity("API_Unit.Models.Tags", b =>
                {
                    b.Navigation("TagRegistereds");
                });
#pragma warning restore 612, 618
        }
    }
}
